# global information, also used in templates/atom.xml
title = "Alex Rutar's Blog"
description = "Personal webpage for math and related topics."
author = "Alex Rutar"

base_url = "https://rutar.org"

# build settings
compile_sass = true
build_search_index = false
generate_feed = true

taxonomies = [
   {name = "tags", paginate = 10}
]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  # {theme = "solarized-light", filename = "syntax.css"},
  # {theme = "subway-madrid", filename = "syntax.css"},
  {theme = "cheerfully-light", filename = "syntax.css"},
]
external_links_target_blank = true
smart_punctuation = true

[extra]
feed_length = 10 # number of elements to show in feed

# extra information renedered on home page
[extra.info]
email = "alex@rutar.org"
keyid = "EE53A00E"
fingerprint = "4B75B74978D18070E5A67BDE0FC554378AEAD4AF"
uni = "ar339@st-andrews.ac.uk"
github = "alexrutar"
orcid = "0000-0001-5173-992X"
mrid = "1432308"
arxiv = "rutar_a_1"
zbmath = "rutar.alex"
