base_url = "https://rutar.org"
compile_sass = true
build_search_index = false

taxonomies = [
   { name = "tags", paginate = 10}
]

[markdown]
highlight_code = false

[extra]
# Put all your custom variables here
author = "Alex Rutar"
description = "Personal webpage for math and related topics."

[extra.info]
email = "alex@rutar.org"
keyid = "EE53A00E"
fingerprint = "4B75B74978D18070E5A67BDE0FC554378AEAD4AF"
uni = "ar339@st-andrews.ac.uk"
github = "alexrutar"
orcid = "0000-0001-5173-992X"
mrid = "1432308"
