name: Build Zola Site

on:
  push:
  schedule:
    - cron: '30 10 * * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up Python (via uv)
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Check formatting
        shell: bash
        run: |
          uvx ruff check scripts
          uvx ruff format scripts --check

      - name: Download papers and notes
        run: ./scripts/releases.py
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Generate data
        shell: bash
        run: |
          mkdir --parent data/generated
          ./scripts/pdf_data.py
          ./scripts/past_travel.py

      - name: Cache CV build
        uses: actions/cache@v4
        id: cache-cv
        env:
          cache-name: cache-cv
        with:
          path: static/alex_rutar_cv.pdf
          key: cache-cv-${{ hashFiles('data/papers.json', 'data/talks.json', 'data/cv.json', 'cv/*', 'scripts/cv.py') }}
      - if: ${{ steps.cache-cv.outputs.cache-hit != 'true' }}
        name: Generate CV .tex from template
        run: ./scripts/cv.py
      - if: ${{ steps.cache-cv.outputs.cache-hit != 'true' }}
        name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          work_in_root_file_dir: true
          root_file: "build/alex_rutar_cv.tex"
          post_compile: mv "build/alex_rutar_cv.pdf" "static/"

      - name: Build public HTML with drafts
        uses: shalzz/zola-deploy-action@v0.21.0
        if: github.ref != 'refs/heads/master'
        env:
          BUILD_FLAGS: --drafts
          BUILD_ONLY: true
      - name: Build public HTML
        uses: shalzz/zola-deploy-action@v0.21.0
        if: github.ref == 'refs/heads/master'
        env:
          BUILD_ONLY: true

      - name: Check HTML and CSS
        run: uvx html5validator --root public/ --also-check-css --show-warnings

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          command: pages deploy public "--project-name=rutar" "--branch=${{ github.ref_name }}"
          apiToken: ${{ secrets.CF_API_TOKEN }}
